### PR TITLE
Fix import of closure-action

### LINKED ISSUE #25: closure-action path changed in master
Just a heads up, it looks like the [path](https://github.com/DockYard/ember-route-action-helper/blob/c80ba222025f99f885c376afc107f979505e9e92/addon/-private/internals.js#L3) to the closure-action has [changed in Ember master](https://github.com/emberjs/ember.js/commit/0cd80863fea4bc76b3cdb1296c718a1e2a63aa28)

It's now at `ember-htmlbars/keywords/closure-action` instead of `ember-routing-htmlbars/keywords/closure-action`

Not sure if there's a nice way of checking the path exists, or falling back if it fails?

### PR DESCRIPTION
**Pull request by martndemus**
Fixes #25

### CODE REVIEW

File: addon/-private/internals.js [hunk 1]
```diff
@@ -1,5 +1,11 @@
 import Ember from 'ember';
 
-const ClosureActionModule = Ember.__loader.require('ember-routing-htmlbars/keywords/closure-action');
+let ClosureActionModule;
+
+try {
```
Comment (rwjblue) [inline addon/-private/internals.js]: It would be better to just check if the module is present, instead of try/catch. 

Ember.__loader.registry or something like that

**Comment by mike-north** [comment]
Now that the 2.7-beta has been cut, this is a more pressing issue

**Comment by poteto** [comment]
@martndemus Do you have any spare cycles to work on this? If not I can take over

**Comment by martndemus** [comment]
@poteto Yes, will fix today

**Comment by martndemus** [comment]
@rwjblue is this what you imagined?

**Comment by rwjblue** [comment]
LGTM

**Comment by poteto** [comment]
@homu r+
